### ISSUE TITLE
Missing environment variables when setting up dev environment

### ISSUE THREAD

**Issue by matt852** [ajnart/subs#2]
When following the "Getting Started" part of the README, I run into the following error:

```bash
➜  subs git:(main) ✗ npm run dev

> shawty@0.1.0 dev
> next dev

❌ Invalid environment variables: { DATABASE_URL: [ 'Required' ] }
file:///Users/matt/HomeLab/subs/node_modules/@t3-oss/env-core/dist/index.js:29
        throw new Error("Invalid environment variables");
              ^

Error: Invalid environment variables
    at onValidationError (file:///Users/matt/HomeLab/subs/node_modules/@t3-oss/env-core/dist/index.js:29:15)
    at createEnv (file:///Users/matt/HomeLab/subs/node_modules/@t3-oss/env-core/dist/index.js:35:16)
    at createEnv (file:///Users/matt/HomeLab/subs/node_modules/@t3-oss/env-nextjs/dist/index.js:12:12)
    at file:///Users/matt/HomeLab/subs/src/env.js:4:20
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async file:///Users/matt/HomeLab/subs/next.config.js:5:1

Node.js v22.6.0
```

**Comment by ajnart** [comment]
Thank you for contributing ! @matt852
