### ISSUE TITLE
Issues after docker installation

### ISSUE THREAD

**Issue by Avonae** [ajnart/subs#25]
```
Require stack:
- /app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at /app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at requireNative (/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js:22:10)
    at Object.<anonymous> (/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js:45:5)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js'
```

and 

```
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
```

**Comment by Avonae** [comment]
updated my docker image with `docker pull ghcr.io/ajnart/subs:latest`
got this error now:
 ```
⨯ Error: Cannot find module '@libsql/linux-x64-musl'
Require stack:
- /app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at /app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at requireNative (/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js:22:10)
    at Object.<anonymous> (/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js:45:5)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js'
  ]
}
```

and my changes I made on the page doesn't save again
